trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.13.0' 
  displayName: 'Install Node.js'

- script: |
    rm -rf node_modules
  displayName: 'Delete node_modules'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'npm run build'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Subscription-dev (e7b14a33-75ca-410d-b8eb-428148538466)'
    appType: 'webApp'
    WebAppName: 'DigiTaraStore'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
